name: Discord 알림

on:
  push:
    branches:
      - '**' # 모든 브랜치

jobs:
  notify:
    uses: ESE-Works/.github/.github/workflows/discord-notify-shared.yml@main
    secrets: inherit # Org Secrets 자동 상속
